### ISSUE TITLE
Accept both base64-encoded UUID and its hex-ASCII representation for filtering

### ISSUE THREAD

**Issue by stdedos** [Lartza/SBbrowser#35]
Sponsorblock's "Import/Export All Other Data" started writing UUID like `F0hy6tTKkFqUxy0b2zqWtkZibzevdnnG3X1t`, instead of `4a653a56530d863de58d2b45b8277d6060f7b948d14c26df3be499c6a2aec7c7`.

Allow filtering and/or in-place "decoding" (from either format to "your favorite" one)

**Comment by mchangrh** [comment]
That's not the b64 equivalent, that's the private ID generation code. Segments receive uuids from the server on upload, so they are useless and not browsable

**Comment by stdedos** [comment]
You are probably right. I was looking for a downvoted segment in "Import/Export All Other Data".

Apparently, "somehow" I had an unsubmitted segment AND managed to mess up when I searched by video ID.

Apologies for the quick issue 😓
